cmc added
ichidao/ichi-sdk pull request #27
Opened 2022-10-12 19:44 UTC by SupremeSingh

2022-10-12 19:48 UTC, engineersamuel requested changes

2022-10-12 19:48 UTC, engineersamuel commented on src/external/coinMarketCap.ts
> +}
Remove the ! and handle if undefined

2022-10-12 19:48 UTC, engineersamuel commented on src/external/coinMarketCap.ts
> +    let cmcClient: any = new CoinMarketCap(apiKey);
Avoid use of `any` if at all possible.  Furthermore, remove this here and put it at the top of the file, and remove the apiKey parameter and use the Envs object to reference this

2022-10-12 19:48 UTC, engineersamuel commented on src/utils/env.ts
> +        'It may be necessary to set the environment variable "CMC_API_KEY"\n\tex. export CHAIN_SRC=https://hostname.com/chains/chain_logo_[chainid].[ext]'
the first part of the text is fine, the 2nd part only applies to CHAIN_SRC and does not apply here, remove it.

2022-10-12 20:27 UTC, SupremeSingh commented on src/external/coinMarketCap.ts
> +}
Added if Not block

2022-10-12 20:27 UTC, SupremeSingh commented on src/utils/env.ts
> +        'It may be necessary to set the environment variable "CMC_API_KEY"\n\tex. export CHAIN_SRC=https://hostname.com/chains/chain_logo_[chainid].[ext]'
Fixed

2022-10-13 12:03 UTC, engineersamuel requested changes

2022-10-13 12:03 UTC, engineersamuel commented on src/external/coinMarketCap.ts
> +import { Optional } from 'src/types/optional';
You'll need to do '../types/optional'

2022-10-13 15:13 UTC, SupremeSingh commented on src/external/coinMarketCap.ts
> +import { Optional } from 'src/types/optional';
zwill correct in the next push

2022-10-13 15:19 UTC, engineersamuel approved these changes

2022-10-13 15:19 UTC, merged